CREATE TABLE "api_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"token_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"expires_at" timestamp with time zone,
	"last_used_at" timestamp with time zone,
	"scopes" text DEFAULT 'read' NOT NULL,
	CONSTRAINT "api_tokens_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "invites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"created_by" integer,
	"created_by_username" text DEFAULT '',
	"preset" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"require_2fa" boolean DEFAULT false,
	"expires_at" timestamp with time zone,
	"used_at" timestamp with time zone,
	"used_by" integer,
	"used_by_username" text DEFAULT '',
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "invites_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "login_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "login_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"ip" text DEFAULT '' NOT NULL,
	"attempted_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "recovery_codes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recovery_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"code_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"used_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"role_id" integer NOT NULL,
	"permission" text NOT NULL,
	CONSTRAINT "role_permissions_role_id_permission_pk" PRIMARY KEY("role_id","permission")
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text DEFAULT '',
	"built_in" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"max_cores" integer,
	"max_memory_gb" integer,
	"max_storage_gb" integer,
	CONSTRAINT "roles_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" text PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ssh_connection_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ssh_connection_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"kind" text NOT NULL,
	"attempted_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "token_auth_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "token_auth_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ip" text NOT NULL,
	"attempted_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "two_factor_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "two_factor_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"attempted_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"password" text NOT NULL,
	"is_admin" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"see_all_vms" boolean DEFAULT false,
	"can_operate_all_vms" boolean DEFAULT false,
	"totp_secret" text,
	"totp_enabled" boolean DEFAULT false,
	"require_2fa" boolean DEFAULT false,
	"can_provision" boolean DEFAULT false,
	"can_manage_hosts" boolean DEFAULT false,
	"can_manage_firewalls" boolean DEFAULT false,
	"can_manage_port_forwards" boolean DEFAULT false,
	"can_manage_vlans" boolean DEFAULT false,
	"can_manage_policies" boolean DEFAULT false,
	"can_manage_templates" boolean DEFAULT false,
	"can_manage_users" boolean DEFAULT false,
	"can_manage_assignments" boolean DEFAULT false,
	"can_view_audit_log" boolean DEFAULT false,
	"can_create_vms" boolean DEFAULT false,
	"can_edit_vm_hardware" boolean DEFAULT false,
	"can_manage_websites" boolean DEFAULT false,
	"can_manage_public_ips" boolean DEFAULT false,
	"notify_opt_out" boolean DEFAULT false,
	"role_id" integer,
	"max_cores" integer,
	"max_memory_gb" integer,
	"max_storage_gb" integer,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "webauthn_credentials" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"public_key" "bytea" NOT NULL,
	"counter" integer DEFAULT 0 NOT NULL,
	"transports" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"device_type" text DEFAULT '' NOT NULL,
	"backed_up" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "firewalls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "firewalls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text DEFAULT 'fortigate' NOT NULL,
	"host" text NOT NULL,
	"port" integer DEFAULT 443,
	"api_key" text NOT NULL,
	"vdom" text DEFAULT 'root',
	"parent_interface" text DEFAULT 'fortilink',
	"wan_interface" text DEFAULT 'wan1',
	"vlan_range_start" integer DEFAULT 1001,
	"vlan_range_end" integer DEFAULT 1999,
	"verify_tls" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"lab_vdom_link" text DEFAULT 'lab-root0',
	"root_vdom" text DEFAULT 'root',
	"root_vdom_link" text DEFAULT 'lab-root1',
	"route_gateway" text DEFAULT '10.255.254.2',
	"trunk_switch_serial" text DEFAULT '',
	"trunk_switch_port" text DEFAULT '',
	"external_ip" text DEFAULT '',
	"root_wan_zone" text DEFAULT 'underlay'
);
--> statement-breakpoint
CREATE TABLE "node_maintenance" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "node_maintenance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pve_host_id" integer,
	"node_name" text NOT NULL,
	"reason" text DEFAULT '',
	"until" timestamp with time zone,
	"notice_id" integer,
	"created_by" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "portal_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portal_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" text NOT NULL,
	"url" text NOT NULL,
	"description" text DEFAULT '',
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "portal_notices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portal_notices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"body" text DEFAULT '',
	"level" text DEFAULT 'info',
	"active" boolean DEFAULT true,
	"created_by" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"source" text DEFAULT ''
);
--> statement-breakpoint
CREATE TABLE "pve_hosts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pve_hosts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"host" text NOT NULL,
	"port" integer DEFAULT 8006,
	"token_id" text NOT NULL,
	"token_secret" text NOT NULL,
	"verify_tls" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"ssh_host" text DEFAULT '',
	"ssh_port" integer DEFAULT 22,
	"ssh_user" text DEFAULT 'root',
	"ssh_auth_type" text DEFAULT 'key',
	"ssh_secret" text DEFAULT '',
	"ssh_host_key" text DEFAULT ''
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "storage_visibility" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "storage_visibility_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pve_host_id" integer NOT NULL,
	"storage" text NOT NULL,
	"exposed" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_vlans" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_vlans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"vlan_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vlans" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vlans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"tag" integer NOT NULL,
	"mode" text DEFAULT 'managed',
	"subnet_cidr" text DEFAULT '',
	"description" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "vlans_tag_unique" UNIQUE("tag")
);
--> statement-breakpoint
CREATE TABLE "cloud_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cloud_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"url" text NOT NULL,
	"node" text NOT NULL,
	"storage" text NOT NULL,
	"volid" text DEFAULT '',
	"size" integer DEFAULT 0,
	"status" text DEFAULT 'downloading',
	"status_detail" text DEFAULT '',
	"upid" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"default_storage" text DEFAULT '',
	"default_storage_map" jsonb,
	"console_patch_status" text DEFAULT '',
	"console_patch_detail" text DEFAULT '',
	"request_id" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "isos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "isos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"url" text NOT NULL,
	"node" text NOT NULL,
	"storage" text NOT NULL,
	"volid" text DEFAULT '',
	"size" integer DEFAULT 0,
	"status" text DEFAULT 'downloading',
	"status_detail" text DEFAULT '',
	"upid" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"request_id" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "provisioned_vms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provisioned_vms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"node" text NOT NULL,
	"vmid" integer NOT NULL,
	"name" text NOT NULL,
	"template_id" integer,
	"source_type" text DEFAULT 'template',
	"cloud_image_id" integer,
	"steps" jsonb,
	"status" text DEFAULT 'creating',
	"status_detail" text DEFAULT '',
	"upid" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"request_id" text DEFAULT '' NOT NULL,
	"upstream_status" text DEFAULT '' NOT NULL,
	"upstream_checked_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ssh_keys" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ssh_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"private_key" text NOT NULL,
	"public_key" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "vm_assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vm_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"node" text NOT NULL,
	"vmid" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vm_leases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vm_leases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"node" text NOT NULL,
	"vmid" integer NOT NULL,
	"lease_days" integer DEFAULT 0,
	"started_at" timestamp with time zone DEFAULT now(),
	"expires_at" timestamp with time zone,
	"renewal_count" integer DEFAULT 0,
	"last_renewed_at" timestamp with time zone,
	"exempt" boolean DEFAULT false,
	"expired" boolean DEFAULT false,
	"expired_at" timestamp with time zone,
	"auto_stopped" boolean DEFAULT false,
	"created_by" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "vm_migrations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vm_migrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"vmid" integer NOT NULL,
	"name" text DEFAULT '',
	"vmtype" text DEFAULT 'qemu',
	"source_node" text NOT NULL,
	"target_node" text NOT NULL,
	"target_storage" text DEFAULT '',
	"target_bridge" text DEFAULT '',
	"online" boolean DEFAULT false,
	"delete_source" boolean DEFAULT true,
	"status" text DEFAULT 'running',
	"status_detail" text DEFAULT '',
	"upid" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"finished_at" timestamp with time zone,
	"mode" text DEFAULT 'remote_migrate',
	"steps" jsonb,
	"kept_source" boolean DEFAULT false,
	"progress" double precision,
	"progress_detail" text DEFAULT '',
	"log_offset" integer DEFAULT 0,
	"request_id" text DEFAULT '' NOT NULL,
	"upstream_status" text DEFAULT '' NOT NULL,
	"upstream_checked_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vm_schedules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vm_schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"node" text NOT NULL,
	"vmid" integer NOT NULL,
	"enabled" boolean DEFAULT true,
	"stop_time" text DEFAULT '',
	"start_time" text DEFAULT '',
	"days" smallint DEFAULT 127,
	"timezone" text DEFAULT 'UTC',
	"skip_until" bigint DEFAULT 0,
	"running_due_to_manual" boolean DEFAULT false,
	"stopped_this_window" boolean DEFAULT false,
	"last_off" smallint DEFAULT -1,
	"last_action" text DEFAULT '',
	"last_action_at" bigint DEFAULT 0,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "vm_ssh_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vm_ssh_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"node" text NOT NULL,
	"vmid" integer NOT NULL,
	"host" text NOT NULL,
	"port" integer DEFAULT 22,
	"host_fingerprint" text DEFAULT '',
	"username" text DEFAULT 'root'
);
--> statement-breakpoint
CREATE TABLE "vm_ssh_user_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vm_ssh_user_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"node" text NOT NULL,
	"vmid" integer NOT NULL,
	"username" text DEFAULT 'root'
);
--> statement-breakpoint
CREATE TABLE "vm_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vm_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text DEFAULT '',
	"node" text NOT NULL,
	"vmid" integer NOT NULL,
	"default_cores" integer DEFAULT 2,
	"default_memory" integer DEFAULT 2048,
	"default_disk_gb" integer DEFAULT 20,
	"default_storage" text DEFAULT 'local-lvm',
	"cloud_init" boolean DEFAULT false,
	"enabled" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "firewall_vlan_sync" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "firewall_vlan_sync_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firewall_id" integer NOT NULL,
	"vlan_id" integer NOT NULL,
	"interface_name" text NOT NULL,
	"policy_ids" jsonb DEFAULT '[]'::jsonb,
	"dhcp_server_id" integer,
	"synced_at" timestamp with time zone DEFAULT now(),
	"artifacts" jsonb,
	"workflow_run_id" integer
);
--> statement-breakpoint
CREATE TABLE "managed_vips" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "managed_vips_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firewall_id" integer NOT NULL,
	"vip_name" text NOT NULL,
	"policy_id" integer,
	"service_name" text DEFAULT '',
	"protocol" text DEFAULT 'tcp',
	"ext_port" integer NOT NULL,
	"mapped_ip" text NOT NULL,
	"mapped_port" integer NOT NULL,
	"dst_interface" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"lab_policy_id" integer,
	"vlan_interface" text DEFAULT '',
	"artifacts" jsonb,
	"workflow_run_id" integer,
	"public_ip_id" integer
);
--> statement-breakpoint
CREATE TABLE "public_ip_assignments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "public_ip_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"public_ip_id" integer NOT NULL,
	"firewall_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"proxmox_host_id" integer,
	"node" text DEFAULT '',
	"vmid" integer,
	"private_ip" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"status_detail" text DEFAULT '',
	"egress_enabled" boolean DEFAULT true,
	"provision_run_id" integer,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "public_ip_pools" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "public_ip_pools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firewall_id" integer NOT NULL,
	"name" text NOT NULL,
	"vdom" text DEFAULT 'root',
	"external_interface" text NOT NULL,
	"gre_gateway" text DEFAULT '',
	"lab_ingress_interface" text DEFAULT '',
	"cidr" text DEFAULT '',
	"mtu" integer,
	"tcp_mss" integer,
	"kill_switch_enabled" boolean DEFAULT true,
	"enabled" boolean DEFAULT true,
	"notes" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "public_ips" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "public_ips_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pool_id" integer NOT NULL,
	"firewall_id" integer NOT NULL,
	"address" text NOT NULL,
	"state" text DEFAULT 'available' NOT NULL,
	"reserved_reason" text DEFAULT '',
	"notes" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "caddy_servers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "caddy_servers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"api_url" text NOT NULL,
	"auth_type" text DEFAULT 'none',
	"auth_secret" text DEFAULT '',
	"server_name" text DEFAULT '',
	"verify_tls" boolean DEFAULT true,
	"wan_ip" text DEFAULT '',
	"fortigate_id" integer,
	"inspection_profile" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"ssh_host" text DEFAULT '',
	"ssh_port" integer DEFAULT 22,
	"ssh_user" text DEFAULT '',
	"ssh_auth_type" text DEFAULT 'key',
	"ssh_secret" text DEFAULT '',
	"ssh_host_key" text DEFAULT '',
	"snippet_path" text DEFAULT '/etc/caddy/homelabrrr.caddy',
	"caddyfile_path" text DEFAULT '/etc/caddy/Caddyfile',
	"inspection_bundle_cert" text DEFAULT ''
);
--> statement-breakpoint
CREATE TABLE "caddy_sites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "caddy_sites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"server_id" integer NOT NULL,
	"domain" text NOT NULL,
	"upstream_host" text NOT NULL,
	"upstream_port" integer DEFAULT 80 NOT NULL,
	"owner_user_id" integer,
	"status" text DEFAULT 'pending',
	"status_detail" text DEFAULT '',
	"steps" jsonb,
	"fortigate_id" integer,
	"inspection_profile" text DEFAULT '',
	"cert_name" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"managed" boolean DEFAULT true,
	"kind" text DEFAULT 'reverse_proxy',
	"wildcard" text DEFAULT '',
	"probe_status" text DEFAULT '',
	"probe_http_status" integer DEFAULT 0,
	"probe_detail" text DEFAULT '',
	"probe_at" timestamp with time zone,
	CONSTRAINT "caddy_sites_domain_unique" UNIQUE("domain")
);
--> statement-breakpoint
CREATE TABLE "workflow_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workflow_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workflow_id" integer,
	"firewall_id" integer,
	"trigger" text DEFAULT '',
	"subject_type" text DEFAULT '',
	"subject_id" text DEFAULT '',
	"subject_label" text DEFAULT '',
	"status" text DEFAULT 'pending',
	"log" jsonb DEFAULT '[]'::jsonb,
	"artifacts" jsonb DEFAULT '[]'::jsonb,
	"dry_run" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	"request_id" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workflow_steps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workflow_steps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workflow_id" integer NOT NULL,
	"position" integer NOT NULL,
	"step_key" text DEFAULT '',
	"action" text NOT NULL,
	"label" text DEFAULT '',
	"params" jsonb DEFAULT '{}'::jsonb,
	"condition" text DEFAULT '',
	"enabled" boolean DEFAULT true,
	"continue_on_error" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "workflows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workflows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firewall_id" integer NOT NULL,
	"trigger" text NOT NULL,
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true,
	"is_default" boolean DEFAULT true,
	"settings" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"username" text NOT NULL,
	"action" text NOT NULL,
	"target" text DEFAULT '',
	"detail" text DEFAULT '',
	"ip" text DEFAULT '',
	"created_at" timestamp with time zone DEFAULT now(),
	"request_id" text DEFAULT '' NOT NULL,
	"outcome" text DEFAULT 'success' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "backup_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "backup_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"path" text DEFAULT '' NOT NULL,
	"size_bytes" bigint DEFAULT 0 NOT NULL,
	"status" text NOT NULL,
	"detail" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"verified_at" timestamp with time zone,
	"request_id" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "backup_tasks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "backup_tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"node" text NOT NULL,
	"vmid" integer NOT NULL,
	"upid" text NOT NULL,
	"storage" text DEFAULT '',
	"status" text DEFAULT 'running',
	"status_detail" text DEFAULT '',
	"progress" double precision,
	"progress_detail" text DEFAULT '',
	"log_offset" integer DEFAULT 0,
	"started_epoch" bigint DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now(),
	"finished_at" timestamp with time zone,
	"request_id" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification_webhooks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_webhooks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"url" text NOT NULL,
	"event_types" jsonb DEFAULT '[]'::jsonb,
	"enabled" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "api_tokens" ADD CONSTRAINT "api_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_used_by_users_id_fk" FOREIGN KEY ("used_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recovery_codes" ADD CONSTRAINT "recovery_codes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ssh_connection_attempts" ADD CONSTRAINT "ssh_connection_attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webauthn_credentials" ADD CONSTRAINT "webauthn_credentials_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "node_maintenance" ADD CONSTRAINT "node_maintenance_notice_id_portal_notices_id_fk" FOREIGN KEY ("notice_id") REFERENCES "public"."portal_notices"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "storage_visibility" ADD CONSTRAINT "storage_visibility_pve_host_id_pve_hosts_id_fk" FOREIGN KEY ("pve_host_id") REFERENCES "public"."pve_hosts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_vlans" ADD CONSTRAINT "user_vlans_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_vlans" ADD CONSTRAINT "user_vlans_vlan_id_vlans_id_fk" FOREIGN KEY ("vlan_id") REFERENCES "public"."vlans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provisioned_vms" ADD CONSTRAINT "provisioned_vms_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provisioned_vms" ADD CONSTRAINT "provisioned_vms_template_id_vm_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."vm_templates"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provisioned_vms" ADD CONSTRAINT "provisioned_vms_cloud_image_id_cloud_images_id_fk" FOREIGN KEY ("cloud_image_id") REFERENCES "public"."cloud_images"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ssh_keys" ADD CONSTRAINT "ssh_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vm_assignments" ADD CONSTRAINT "vm_assignments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vm_ssh_user_configs" ADD CONSTRAINT "vm_ssh_user_configs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "firewall_vlan_sync" ADD CONSTRAINT "firewall_vlan_sync_firewall_id_firewalls_id_fk" FOREIGN KEY ("firewall_id") REFERENCES "public"."firewalls"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "firewall_vlan_sync" ADD CONSTRAINT "firewall_vlan_sync_vlan_id_vlans_id_fk" FOREIGN KEY ("vlan_id") REFERENCES "public"."vlans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "firewall_vlan_sync" ADD CONSTRAINT "firewall_vlan_sync_workflow_run_id_workflow_runs_id_fk" FOREIGN KEY ("workflow_run_id") REFERENCES "public"."workflow_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "managed_vips" ADD CONSTRAINT "managed_vips_firewall_id_firewalls_id_fk" FOREIGN KEY ("firewall_id") REFERENCES "public"."firewalls"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "managed_vips" ADD CONSTRAINT "managed_vips_workflow_run_id_workflow_runs_id_fk" FOREIGN KEY ("workflow_run_id") REFERENCES "public"."workflow_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "public_ip_assignments" ADD CONSTRAINT "public_ip_assignments_public_ip_id_public_ips_id_fk" FOREIGN KEY ("public_ip_id") REFERENCES "public"."public_ips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "public_ip_assignments" ADD CONSTRAINT "public_ip_assignments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "public_ip_pools" ADD CONSTRAINT "public_ip_pools_firewall_id_firewalls_id_fk" FOREIGN KEY ("firewall_id") REFERENCES "public"."firewalls"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "public_ips" ADD CONSTRAINT "public_ips_pool_id_public_ip_pools_id_fk" FOREIGN KEY ("pool_id") REFERENCES "public"."public_ip_pools"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caddy_servers" ADD CONSTRAINT "caddy_servers_fortigate_id_firewalls_id_fk" FOREIGN KEY ("fortigate_id") REFERENCES "public"."firewalls"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caddy_sites" ADD CONSTRAINT "caddy_sites_server_id_caddy_servers_id_fk" FOREIGN KEY ("server_id") REFERENCES "public"."caddy_servers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caddy_sites" ADD CONSTRAINT "caddy_sites_owner_user_id_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caddy_sites" ADD CONSTRAINT "caddy_sites_fortigate_id_firewalls_id_fk" FOREIGN KEY ("fortigate_id") REFERENCES "public"."firewalls"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workflow_runs" ADD CONSTRAINT "workflow_runs_workflow_id_workflows_id_fk" FOREIGN KEY ("workflow_id") REFERENCES "public"."workflows"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workflow_steps" ADD CONSTRAINT "workflow_steps_workflow_id_workflows_id_fk" FOREIGN KEY ("workflow_id") REFERENCES "public"."workflows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workflows" ADD CONSTRAINT "workflows_firewall_id_firewalls_id_fk" FOREIGN KEY ("firewall_id") REFERENCES "public"."firewalls"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_api_tokens_hash" ON "api_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "idx_api_tokens_user" ON "api_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_invites_created_by" ON "invites" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_invites_used_by" ON "invites" USING btree ("used_by");--> statement-breakpoint
CREATE INDEX "idx_login_attempts" ON "login_attempts" USING btree ("username","attempted_at");--> statement-breakpoint
CREATE INDEX "idx_login_attempts_ip" ON "login_attempts" USING btree ("username","ip","attempted_at");--> statement-breakpoint
CREATE UNIQUE INDEX "recovery_codes_user_id_code_hash_unique" ON "recovery_codes" USING btree ("user_id","code_hash");--> statement-breakpoint
CREATE INDEX "idx_recovery_codes_user" ON "recovery_codes" USING btree ("user_id","used_at");--> statement-breakpoint
CREATE INDEX "idx_sessions_expire" ON "sessions" USING btree ("expire");--> statement-breakpoint
CREATE INDEX "idx_ssh_connection_attempts_user" ON "ssh_connection_attempts" USING btree ("user_id","kind","attempted_at");--> statement-breakpoint
CREATE INDEX "idx_token_auth_attempts" ON "token_auth_attempts" USING btree ("ip","attempted_at");--> statement-breakpoint
CREATE INDEX "idx_two_factor_attempts" ON "two_factor_attempts" USING btree ("username","attempted_at");--> statement-breakpoint
CREATE INDEX "idx_users_role" ON "users" USING btree ("role_id");--> statement-breakpoint
CREATE UNIQUE INDEX "webauthn_credentials_user_id_name_unique" ON "webauthn_credentials" USING btree ("user_id","name");--> statement-breakpoint
CREATE INDEX "idx_webauthn_credentials_user" ON "webauthn_credentials" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_node_maintenance_notice" ON "node_maintenance" USING btree ("notice_id");--> statement-breakpoint
CREATE UNIQUE INDEX "storage_visibility_pve_host_id_storage_unique" ON "storage_visibility" USING btree ("pve_host_id","storage");--> statement-breakpoint
CREATE UNIQUE INDEX "user_vlans_user_id_vlan_id_unique" ON "user_vlans" USING btree ("user_id","vlan_id");--> statement-breakpoint
CREATE INDEX "idx_user_vlans_vlan" ON "user_vlans" USING btree ("vlan_id");--> statement-breakpoint
CREATE INDEX "idx_provisioned_vms_user" ON "provisioned_vms" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_provisioned_vms_status" ON "provisioned_vms" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_provisioned_vms_cloud_image" ON "provisioned_vms" USING btree ("cloud_image_id");--> statement-breakpoint
CREATE INDEX "idx_provisioned_vms_template" ON "provisioned_vms" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "idx_ssh_keys_user" ON "ssh_keys" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "vm_assignments_node_vmid_unique" ON "vm_assignments" USING btree ("node","vmid");--> statement-breakpoint
CREATE INDEX "idx_vm_assignments_user" ON "vm_assignments" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "vm_leases_node_vmid_unique" ON "vm_leases" USING btree ("node","vmid");--> statement-breakpoint
CREATE INDEX "idx_vm_migrations_status" ON "vm_migrations" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "vm_schedules_node_vmid_unique" ON "vm_schedules" USING btree ("node","vmid");--> statement-breakpoint
CREATE UNIQUE INDEX "vm_ssh_configs_node_vmid_unique" ON "vm_ssh_configs" USING btree ("node","vmid");--> statement-breakpoint
CREATE UNIQUE INDEX "vm_ssh_user_configs_user_node_vmid_unique" ON "vm_ssh_user_configs" USING btree ("user_id","node","vmid");--> statement-breakpoint
CREATE UNIQUE INDEX "vm_templates_node_vmid_unique" ON "vm_templates" USING btree ("node","vmid");--> statement-breakpoint
CREATE UNIQUE INDEX "firewall_vlan_sync_firewall_id_vlan_id_unique" ON "firewall_vlan_sync" USING btree ("firewall_id","vlan_id");--> statement-breakpoint
CREATE INDEX "idx_firewall_vlan_sync_run" ON "firewall_vlan_sync" USING btree ("workflow_run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "managed_vips_firewall_id_vip_name_unique" ON "managed_vips" USING btree ("firewall_id","vip_name");--> statement-breakpoint
CREATE INDEX "idx_managed_vips_public_ip" ON "managed_vips" USING btree ("public_ip_id");--> statement-breakpoint
CREATE INDEX "idx_managed_vips_endpoint" ON "managed_vips" USING btree ("firewall_id","public_ip_id","protocol","ext_port");--> statement-breakpoint
CREATE INDEX "idx_managed_vips_workflow_run" ON "managed_vips" USING btree ("workflow_run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_public_ip_assignments_ip" ON "public_ip_assignments" USING btree ("public_ip_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_public_ip_assignments_egress" ON "public_ip_assignments" USING btree ("firewall_id","private_ip") WHERE egress_enabled;--> statement-breakpoint
CREATE INDEX "idx_public_ip_assignments_user" ON "public_ip_assignments" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "public_ip_pools_firewall_id_name_unique" ON "public_ip_pools" USING btree ("firewall_id","name");--> statement-breakpoint
CREATE INDEX "idx_public_ip_pools_fw" ON "public_ip_pools" USING btree ("firewall_id");--> statement-breakpoint
CREATE UNIQUE INDEX "public_ips_pool_id_address_unique" ON "public_ips" USING btree ("pool_id","address");--> statement-breakpoint
CREATE UNIQUE INDEX "public_ips_firewall_id_address_unique" ON "public_ips" USING btree ("firewall_id","address");--> statement-breakpoint
CREATE INDEX "idx_public_ips_pool" ON "public_ips" USING btree ("pool_id");--> statement-breakpoint
CREATE INDEX "idx_public_ips_state" ON "public_ips" USING btree ("pool_id","state");--> statement-breakpoint
CREATE INDEX "idx_caddy_sites_server" ON "caddy_sites" USING btree ("server_id");--> statement-breakpoint
CREATE INDEX "idx_caddy_sites_owner" ON "caddy_sites" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "idx_caddy_sites_fortigate" ON "caddy_sites" USING btree ("fortigate_id");--> statement-breakpoint
CREATE INDEX "idx_workflow_runs_wf" ON "workflow_runs" USING btree ("workflow_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_workflow_runs_subject" ON "workflow_runs" USING btree ("firewall_id","subject_type","subject_id");--> statement-breakpoint
CREATE INDEX "idx_workflow_runs_created" ON "workflow_runs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_workflow_steps_wf" ON "workflow_steps" USING btree ("workflow_id","position");--> statement-breakpoint
CREATE UNIQUE INDEX "workflows_firewall_id_trigger_unique" ON "workflows" USING btree ("firewall_id","trigger");--> statement-breakpoint
CREATE INDEX "idx_audit_log_created" ON "audit_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_audit_log_user" ON "audit_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_backup_tasks_vm" ON "backup_tasks" USING btree ("node","vmid");--> statement-breakpoint
CREATE INDEX "idx_backup_tasks_created" ON "backup_tasks" USING btree ("created_at");