CREATE TABLE hardware_connections (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pve_host_id integer NOT NULL REFERENCES pve_hosts(id) ON DELETE RESTRICT,
  node_ref text NOT NULL,
  target_host text NOT NULL,
  target_port integer NOT NULL DEFAULT 443 CHECK (target_port BETWEEN 1 AND 65535),
  username text NOT NULL,
  secret text NOT NULL,
  ca_certificate text,
  verify_tls boolean NOT NULL DEFAULT true,
  collection_enabled boolean NOT NULL DEFAULT false,
  control_enabled boolean NOT NULL DEFAULT false,
  lifecycle_state text NOT NULL DEFAULT 'active' CHECK (lifecycle_state IN ('active', 'decommissioned')),
  config_version integer NOT NULL DEFAULT 1,
  system_uuid text,
  model text,
  generation text,
  firmware text,
  capabilities jsonb,
  last_status text NOT NULL DEFAULT 'not_tested',
  last_test_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX hardware_connections_active_node_unique ON hardware_connections(node_ref) WHERE lifecycle_state = 'active';
CREATE UNIQUE INDEX hardware_connections_active_system_unique ON hardware_connections(system_uuid) WHERE lifecycle_state = 'active' AND system_uuid IS NOT NULL;
CREATE INDEX hardware_connections_host_idx ON hardware_connections(pve_host_id);
