CREATE TABLE "eloverblik_charge_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eloverblik_charge_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"meter_id" text NOT NULL,
	"content_hash" text NOT NULL,
	"source_payload" jsonb NOT NULL,
	"observed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "eloverblik_connections" (
	"id" integer PRIMARY KEY NOT NULL,
	"refresh_token" text,
	"config_version" integer DEFAULT 1 NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"selected_meter_id" text,
	"meter_scope" text DEFAULT 'household' NOT NULL,
	"import_cursor" timestamp with time zone,
	"last_attempt_at" timestamp with time zone,
	"last_success_at" timestamp with time zone,
	"latest_interval_end" timestamp with time zone,
	"last_error_code" text
);
--> statement-breakpoint
CREATE TABLE "eloverblik_intervals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eloverblik_intervals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"meter_id" text NOT NULL,
	"series_key" text NOT NULL,
	"business_type" text NOT NULL,
	"aggregation" text NOT NULL,
	"resolution" text NOT NULL,
	"interval_start" timestamp with time zone NOT NULL,
	"interval_end" timestamp with time zone NOT NULL,
	"energy_kwh" numeric(20, 6),
	"quality" text,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "eloverblik_charge_version" ON "eloverblik_charge_snapshots" USING btree ("meter_id","content_hash");--> statement-breakpoint
CREATE INDEX "eloverblik_charge_recent" ON "eloverblik_charge_snapshots" USING btree ("meter_id","observed_at");--> statement-breakpoint
CREATE UNIQUE INDEX "eloverblik_interval_identity" ON "eloverblik_intervals" USING btree ("meter_id","series_key","aggregation","interval_start","interval_end");--> statement-breakpoint
CREATE INDEX "eloverblik_interval_range" ON "eloverblik_intervals" USING btree ("meter_id","interval_start");
