CREATE TABLE hardware_telemetry_state (
  hardware_id integer PRIMARY KEY REFERENCES hardware_connections(id) ON DELETE CASCADE,
  lease_until timestamptz,
  next_poll_at timestamptz NOT NULL DEFAULT now(),
  failure_count integer NOT NULL DEFAULT 0,
  last_error_code text,
  last_attempt_at timestamptz,
  last_success_at timestamptz
);
CREATE TABLE hardware_power_samples (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hardware_id integer NOT NULL REFERENCES hardware_connections(id) ON DELETE RESTRICT,
  node_ref text NOT NULL,
  observed_at timestamptz NOT NULL,
  watts numeric(12,3) NOT NULL CHECK (watts >= 0 AND watts <= 100000),
  mode text NOT NULL,
  origin text NOT NULL,
  device_epoch text,
  quality text NOT NULL DEFAULT 'instantaneous'
);
CREATE UNIQUE INDEX hardware_power_sample_identity ON hardware_power_samples(hardware_id, observed_at);
CREATE INDEX hardware_power_sample_range ON hardware_power_samples(hardware_id, observed_at);
CREATE TABLE hardware_energy_intervals (
  hardware_id integer NOT NULL REFERENCES hardware_connections(id) ON DELETE RESTRICT,
  start_utc timestamptz NOT NULL,
  end_utc timestamptz NOT NULL,
  kwh numeric(20,9) NOT NULL CHECK (kwh >= 0),
  covered_seconds integer NOT NULL CHECK (covered_seconds BETWEEN 0 AND 900),
  expected_seconds integer NOT NULL DEFAULT 900,
  quality text NOT NULL,
  method_version text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_utc > start_utc)
);
CREATE UNIQUE INDEX hardware_energy_interval_identity ON hardware_energy_intervals(hardware_id, start_utc);
CREATE INDEX hardware_energy_interval_range ON hardware_energy_intervals(hardware_id, start_utc);
CREATE TABLE hardware_energy_days (
  hardware_id integer NOT NULL REFERENCES hardware_connections(id) ON DELETE RESTRICT,
  local_date date NOT NULL,
  kwh numeric(20,9) NOT NULL CHECK (kwh >= 0),
  covered_seconds integer NOT NULL,
  expected_seconds integer NOT NULL,
  quality text NOT NULL,
  method_version text NOT NULL
);
CREATE UNIQUE INDEX hardware_energy_day_identity ON hardware_energy_days(hardware_id, local_date);
