CREATE TABLE "hardware_power_operations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hardware_power_operations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hardware_id" integer NOT NULL,
	"actor" text NOT NULL,
	"prior_mode" text,
	"target_mode" text,
	"reason" text NOT NULL,
	"outcome" text NOT NULL,
	"policy_version" integer NOT NULL,
	"price_revision" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hardware_power_policies" (
	"hardware_id" integer PRIMARY KEY NOT NULL,
	"automation_enabled" boolean DEFAULT false NOT NULL,
	"paused" boolean DEFAULT false NOT NULL,
	"drift_hold" boolean DEFAULT false NOT NULL,
	"schedule" jsonb NOT NULL,
	"price_policy" jsonb NOT NULL,
	"manual_mode" text,
	"manual_expires_at" timestamp with time zone,
	"latch" jsonb,
	"claim_token" text,
	"claim_expires_at" timestamp with time zone,
	"last_verified_mode" text,
	"last_outcome" text,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "hardware_power_operations" ADD CONSTRAINT "hardware_power_operations_hardware_id_hardware_connections_id_fk" FOREIGN KEY ("hardware_id") REFERENCES "public"."hardware_connections"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hardware_power_policies" ADD CONSTRAINT "hardware_power_policies_hardware_id_hardware_connections_id_fk" FOREIGN KEY ("hardware_id") REFERENCES "public"."hardware_connections"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "hardware_power_operations_history_idx" ON "hardware_power_operations" USING btree ("hardware_id","occurred_at");--> statement-breakpoint
CREATE INDEX "hardware_power_policies_claim_idx" ON "hardware_power_policies" USING btree ("claim_expires_at");
