CREATE TABLE "electricity_bills" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electricity_bills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"period_end" timestamp with time zone NOT NULL,
	"amount_ore" integer NOT NULL,
	"billed_kwh" numeric(20, 6),
	"status" text DEFAULT 'due' NOT NULL,
	"paid_at" timestamp with time zone,
	"paid_ore" integer,
	"reference" text,
	"note" text,
	"kind" text DEFAULT 'settlement' NOT NULL,
	"finalized" boolean DEFAULT false NOT NULL,
	"revision" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "electricity_contracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electricity_contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" text NOT NULL,
	"kind" text NOT NULL,
	"area" text NOT NULL,
	"valid_from" timestamp with time zone NOT NULL,
	"valid_to" timestamp with time zone,
	"fixed_dkk_per_kwh" numeric(12, 6),
	"spot_margin_dkk_per_kwh" numeric(12, 6),
	"vat_rate" numeric(8, 6),
	"required_components" jsonb,
	"fixed_monthly_ore" integer,
	"fixed_fee_allocation" text DEFAULT 'none' NOT NULL,
	"fixed_fee_manual_share" numeric(8, 6),
	"revision" integer DEFAULT 1 NOT NULL,
	"active" boolean DEFAULT false NOT NULL,
	"provenance" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "electricity_cost_statements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electricity_cost_statements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"period_end" timestamp with time zone NOT NULL,
	"revision" integer NOT NULL,
	"previous_id" integer,
	"calculation" jsonb NOT NULL,
	"finalized" boolean DEFAULT true NOT NULL,
	"reason" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "electricity_spot_prices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electricity_spot_prices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"area" text NOT NULL,
	"start_utc" timestamp with time zone NOT NULL,
	"end_utc" timestamp with time zone NOT NULL,
	"dkk_per_kwh" numeric(12, 6) NOT NULL,
	"source_revision" text NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "electricity_tariffs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electricity_tariffs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"component" text NOT NULL,
	"valid_from" timestamp with time zone NOT NULL,
	"valid_to" timestamp with time zone NOT NULL,
	"dkk_per_kwh" numeric(12, 6) NOT NULL,
	"vat_included" boolean DEFAULT false NOT NULL,
	"provenance" text NOT NULL,
	"revision" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "electricity_bills" ADD CONSTRAINT "electricity_bills_contract_id_electricity_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."electricity_contracts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "electricity_cost_statements" ADD CONSTRAINT "electricity_cost_statements_contract_id_electricity_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."electricity_contracts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "electricity_tariffs" ADD CONSTRAINT "electricity_tariffs_contract_id_electricity_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."electricity_contracts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "electricity_bill_period" ON "electricity_bills" USING btree ("contract_id","period_start","period_end");--> statement-breakpoint
CREATE INDEX "electricity_contract_validity" ON "electricity_contracts" USING btree ("active","valid_from","valid_to");--> statement-breakpoint
CREATE UNIQUE INDEX "electricity_statement_revision" ON "electricity_cost_statements" USING btree ("contract_id","period_start","period_end","revision");--> statement-breakpoint
CREATE INDEX "electricity_statement_period" ON "electricity_cost_statements" USING btree ("contract_id","period_start");--> statement-breakpoint
CREATE UNIQUE INDEX "electricity_spot_identity" ON "electricity_spot_prices" USING btree ("area","start_utc");--> statement-breakpoint
CREATE INDEX "electricity_spot_range" ON "electricity_spot_prices" USING btree ("area","start_utc","end_utc");--> statement-breakpoint
CREATE INDEX "electricity_tariff_validity" ON "electricity_tariffs" USING btree ("contract_id","component","valid_from","valid_to");