CREATE TABLE "paypal_configs" (
	"environment" text PRIMARY KEY NOT NULL,
	"client_id" text,
	"client_secret" text,
	"merchant_id" text,
	"webhook_id" text,
	"monthly_plan_id" text,
	"monthly_amount_ore" integer,
	"enabled" boolean DEFAULT false NOT NULL,
	"config_version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "paypal_intents" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" integer,
	"environment" text NOT NULL,
	"merchant_id" text NOT NULL,
	"kind" text NOT NULL,
	"amount_ore" integer NOT NULL,
	"currency" text DEFAULT 'DKK' NOT NULL,
	"status" text DEFAULT 'created' NOT NULL,
	"provider_id" text,
	"create_request_id" text NOT NULL,
	"capture_request_id" text,
	"config_version" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "paypal_postings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "paypal_postings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"environment" text NOT NULL,
	"merchant_id" text NOT NULL,
	"provider_transaction_id" text NOT NULL,
	"posting_kind" text NOT NULL,
	"source_id" text NOT NULL,
	"original_transaction_id" text,
	"intent_id" text,
	"user_id" integer,
	"amount_ore" integer NOT NULL,
	"currency" text NOT NULL,
	"effective_at" timestamp with time zone NOT NULL,
	"posted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"verification" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "paypal_reconciliation" (
	"environment" text PRIMARY KEY NOT NULL,
	"last_run_at" timestamp with time zone,
	"cursor_at" timestamp with time zone,
	"status" text DEFAULT 'idle' NOT NULL,
	"error_code" text
);
--> statement-breakpoint
CREATE TABLE "paypal_subscriptions" (
	"id" text PRIMARY KEY NOT NULL,
	"intent_id" text NOT NULL,
	"user_id" integer,
	"environment" text NOT NULL,
	"merchant_id" text NOT NULL,
	"status" text NOT NULL,
	"plan_id" text NOT NULL,
	"amount_ore" integer NOT NULL,
	"cancellation_requested_at" timestamp with time zone,
	"cancel_request_id" text,
	"cancelled_at" timestamp with time zone,
	"reconciled_through_at" timestamp with time zone,
	"next_billing_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "paypal_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "paypal_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"environment" text NOT NULL,
	"merchant_id" text NOT NULL,
	"provider_transaction_id" text NOT NULL,
	"provider_kind" text NOT NULL,
	"original_transaction_id" text,
	"intent_id" text,
	"user_id" integer,
	"status" text NOT NULL,
	"currency" text NOT NULL,
	"gross_ore" integer,
	"fee_ore" integer,
	"net_ore" integer,
	"effective_at" timestamp with time zone,
	"observed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "paypal_webhook_inbox" (
	"id" text PRIMARY KEY NOT NULL,
	"environment" text NOT NULL,
	"merchant_id" text NOT NULL,
	"event_type" text NOT NULL,
	"resource_id" text,
	"payload" jsonb NOT NULL,
	"source" text DEFAULT 'verified_webhook' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event_at" timestamp with time zone,
	"processing_at" timestamp with time zone,
	"next_attempt_at" timestamp with time zone,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"processed_at" timestamp with time zone,
	"error_code" text
);
--> statement-breakpoint
ALTER TABLE "paypal_intents" ADD CONSTRAINT "paypal_intents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paypal_postings" ADD CONSTRAINT "paypal_postings_intent_id_paypal_intents_id_fk" FOREIGN KEY ("intent_id") REFERENCES "public"."paypal_intents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paypal_postings" ADD CONSTRAINT "paypal_postings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paypal_subscriptions" ADD CONSTRAINT "paypal_subscriptions_intent_id_paypal_intents_id_fk" FOREIGN KEY ("intent_id") REFERENCES "public"."paypal_intents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paypal_subscriptions" ADD CONSTRAINT "paypal_subscriptions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paypal_transactions" ADD CONSTRAINT "paypal_transactions_intent_id_paypal_intents_id_fk" FOREIGN KEY ("intent_id") REFERENCES "public"."paypal_intents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "paypal_transactions" ADD CONSTRAINT "paypal_transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "paypal_intent_provider" ON "paypal_intents" USING btree ("environment","merchant_id","provider_id");--> statement-breakpoint
CREATE UNIQUE INDEX "paypal_intent_create_request" ON "paypal_intents" USING btree ("create_request_id");--> statement-breakpoint
CREATE INDEX "paypal_intent_user_created" ON "paypal_intents" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "paypal_posting_unique_economic" ON "paypal_postings" USING btree ("environment","merchant_id","provider_transaction_id","posting_kind");--> statement-breakpoint
CREATE INDEX "paypal_posting_user_time" ON "paypal_postings" USING btree ("user_id","effective_at");--> statement-breakpoint
CREATE INDEX "paypal_posting_period" ON "paypal_postings" USING btree ("environment","effective_at");--> statement-breakpoint
CREATE INDEX "paypal_subscription_user" ON "paypal_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "paypal_subscription_status" ON "paypal_subscriptions" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "paypal_transaction_identity" ON "paypal_transactions" USING btree ("environment","merchant_id","provider_transaction_id");--> statement-breakpoint
CREATE INDEX "paypal_transaction_unresolved" ON "paypal_transactions" USING btree ("status","observed_at");--> statement-breakpoint
CREATE INDEX "paypal_transaction_intent" ON "paypal_transactions" USING btree ("intent_id");--> statement-breakpoint
CREATE INDEX "paypal_webhook_pending" ON "paypal_webhook_inbox" USING btree ("status","received_at");