CREATE TABLE "paypal_month_allocations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "paypal_month_allocations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"month" text NOT NULL,
	"revision" integer NOT NULL,
	"previous_id" integer,
	"source_fingerprint" text NOT NULL,
	"cost_statement_id" integer,
	"ledger_revision" integer DEFAULT 0 NOT NULL,
	"status" text NOT NULL,
	"cost_ore" integer,
	"received_net_ore" integer NOT NULL,
	"opening_balance_ore" integer,
	"applied_ore" integer,
	"owner_remainder_ore" integer,
	"owner_adjustment_ore" integer,
	"closing_balance_ore" integer,
	"unresolved_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "paypal_month_allocations" ADD CONSTRAINT "paypal_month_allocations_cost_statement_id_electricity_cost_statements_id_fk" FOREIGN KEY ("cost_statement_id") REFERENCES "public"."electricity_cost_statements"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "paypal_month_allocation_revision" ON "paypal_month_allocations" USING btree ("month","revision");--> statement-breakpoint
CREATE INDEX "paypal_month_allocation_month" ON "paypal_month_allocations" USING btree ("month");