CREATE TABLE "electricity_extra_loads" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "electricity_extra_loads_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source_key" text NOT NULL,
	"label" text NOT NULL,
	"estimated_watts" numeric(12, 3) NOT NULL,
	"valid_from" timestamp with time zone NOT NULL,
	"valid_to" timestamp with time zone NOT NULL,
	"excludes_server_energy" boolean NOT NULL,
	"provenance" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "electricity_extra_load_source" ON "electricity_extra_loads" USING btree ("source_key","valid_from","valid_to");--> statement-breakpoint
CREATE INDEX "electricity_extra_load_validity" ON "electricity_extra_loads" USING btree ("valid_from","valid_to");