import { readdir, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pool } from './client.ts';
import { log } from '../utils/logger.ts';

// Tiny migration runner. Numbered SQL files in backend/drizzle/ (generated by
// `npm run db:generate`, hand-trimmed — drizzle-kit output is a draft, never
// gospel) are applied in order inside ONE transaction, guarded by an advisory
// lock so two booting replicas cannot race. Applied versions are recorded in
// schema_migrations, which readiness() and the ops panel also read.
//
// Never edit an applied migration — add a new numbered file.

const MIGRATIONS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'drizzle');

interface MigrationFile {
  version: number;
  name: string;
  path: string;
}

async function listMigrationFiles(): Promise<MigrationFile[]> {
  const entries = await readdir(MIGRATIONS_DIR);
  const files: MigrationFile[] = [];
  for (const name of entries) {
    const match = /^(\d+)_.+\.sql$/.exec(name);
    if (!match) continue;
    files.push({ version: Number(match[1]), name, path: join(MIGRATIONS_DIR, name) });
  }
  files.sort((a, b) => a.version - b.version);
  const seen = new Set<number>();
  for (const f of files) {
    if (seen.has(f.version)) throw new Error(`Duplicate migration version ${f.version} (${f.name})`);
    seen.add(f.version);
  }
  return files;
}

export async function runMigrations(): Promise<number> {
  const files = await listMigrationFiles();
  if (files.length === 0) throw new Error(`No migration files found in ${MIGRATIONS_DIR}`);

  const client = await pool.connect();
  let applied = 0;
  try {
    await client.query('BEGIN');
    // Arbitrary app-wide key ("HLBR"); serializes concurrent boots.
    await client.query('SELECT pg_advisory_xact_lock(1213157458)');
    await client.query(`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        version integer PRIMARY KEY,
        name text NOT NULL,
        applied_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    const { rows } = await client.query('SELECT version FROM schema_migrations');
    const done = new Set(rows.map((r) => Number(r.version)));
    for (const file of files) {
      if (done.has(file.version)) continue;
      const raw = await readFile(file.path, 'utf8');
      // drizzle-kit separates statements with breakpoint comments; the raw
      // text runs fine as one multi-statement simple query once removed.
      const sqlText = raw.replaceAll('--> statement-breakpoint', '');
      await client.query(sqlText);
      await client.query('INSERT INTO schema_migrations (version, name) VALUES ($1, $2)', [file.version, file.name]);
      applied += 1;
      log('info', 'migration_applied', { version: file.version, name: file.name });
    }
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    throw err;
  } finally {
    client.release();
  }
  return applied;
}
