// Pure pre-flight decisions for a cross-host guest migration.
//
// Both helpers take plain data — a guest config object and the Proxmox storage
// definitions the caller already fetched (`getStorageDefs`) — so they hold no
// network or database dependency and can be unit-tested on their own.

// ─── 1. Local CD-ROM media ───────────────────────────────────────────────────

// Drive keys that can carry removable media. `efidisk`/`tpmstate` never can, so
// they are deliberately outside this pattern.
const MEDIA_KEY_RE = /^(?:ide|sata|scsi|virtio)\d+$/;

// Volume references that are not a migratable volume at all:
//   none    — the drive is already empty
//   cdrom   — the node's physical optical drive (/dev/cdrom); Proxmox skips it
//             during the volume scan, so ejecting it would be a user-visible
//             change with no benefit
const EMPTY_MEDIA = new Set(['', 'none', 'cdrom']);

// Which drives must be emptied before Proxmox will accept a cross-host
// migration of this VM.
//
// PVE's `remote_migrate` scans every referenced volume up front and aborts
// phase 1 with "can't migrate local disk '<volid>': local cdrom image" as soon
// as one attached ISO lives on storage the migration cannot carry. There is no
// API parameter to rewrite the drive list for the target — the source ships its
// own config — so the only way through is to empty the drive on the source
// before the migration starts. That is user-visible, which is why the caller
// reports exactly what it ejected.
//
// `sharedStorages` is the set of source storage ids that the target host also
// mounts (same NFS export / CIFS share). An ISO sitting there is reachable from
// the target by the same path, so it is left attached rather than silently
// thrown away.
//
// Returns:
//   keys   — config keys to clear (set each to 'none,media=cdrom')
//   detach — [{ key, volid, storage, value }] for reporting and for restoring
//            the original value if the migration never gets started
//   kept   — CD-ROMs deliberately left alone, with the reason
export function planCdromDetach(vmConfig, { sharedStorages = [] } = {}) {
  const shared = new Set(sharedStorages || []);
  const detach = [];
  const kept = [];

  for (const [key, value] of Object.entries(vmConfig || {})) {
    if (!MEDIA_KEY_RE.test(key) || typeof value !== 'string') continue;
    if (!/(?:^|,)media=cdrom(?:,|$)/.test(value)) continue;

    const volid = value.split(',')[0].trim();
    if (EMPTY_MEDIA.has(volid)) continue;
    // Cloud-init drives are regenerated by Proxmox on the target — the volume
    // scan lets them through and clearing one would drop the VM's seed data.
    if (/cloudinit/.test(volid)) continue;

    const storage = volid.includes(':') ? volid.split(':')[0] : '';
    if (storage && shared.has(storage)) {
      kept.push({ key, volid, storage, reason: 'on storage the target host also mounts' });
      continue;
    }
    detach.push({ key, volid, storage, value });
  }

  detach.sort((a, b) => a.key.localeCompare(b.key));
  kept.sort((a, b) => a.key.localeCompare(b.key));
  return { keys: detach.map((d) => d.key), detach, kept };
}

// ─── 2. Target storage compatibility ─────────────────────────────────────────

// How a storage type keeps a *container* volume. Proxmox negotiates an
// import/export stream format per volume, and the two families have no format
// in common: a subvolume/dataset is streamed as `tar+size`, a raw disk image as
// `raw+size`. Crossing families is what produces
//   "no matching import/export format found for storage '<id>'"
// mid-transfer, after the container has already been stopped.
const CT_SUBVOL_TYPES = new Set(['zfspool', 'btrfs']);
const CT_IMAGE_TYPES = new Set(['lvm', 'lvmthin', 'rbd', 'zfs', 'iscsi', 'iscsidirect']);
// File-based storages hold either shape (`subvol-…` directory or a `.raw`
// image file), so they accept both stream formats.
const CT_FILE_TYPES = new Set(['dir', 'nfs', 'cifs', 'cephfs', 'glusterfs']);

function targetCtFamilies(type) {
  if (CT_SUBVOL_TYPES.has(type)) return new Set(['subvol']);
  if (CT_IMAGE_TYPES.has(type)) return new Set(['image']);
  if (CT_FILE_TYPES.has(type)) return new Set(['subvol', 'image']);
  return null; // unknown plugin — do not guess
}

// The family of one source volume, read from the volume name first (it is
// authoritative: `subvol-107-disk-0` vs `vm-107-disk-0[.raw]`) and from the
// source storage type only as a fallback.
function sourceCtFamily(volid, storageType) {
  const volname = String(volid || '').split(':').slice(1).join(':');
  const base = volname.split('/').pop() || '';
  if (/^subvol-/.test(base)) return 'subvol';
  if (/^vm-\d+-disk-/.test(base)) return 'image';
  if (CT_SUBVOL_TYPES.has(storageType)) return 'subvol';
  if (CT_IMAGE_TYPES.has(storageType)) return 'image';
  return null; // file storage without a recognizable name — ambiguous
}

const ok = () => ({ ok: true, severity: 'ok', reason: '' });
const warn = (reason) => ({ ok: true, severity: 'warn', reason });
const block = (reason) => ({ ok: false, severity: 'error', reason });

// Can `targetStorageDef` actually receive the guest's volumes?
//
// This runs before the guest is touched. A migration that fails on storage
// grounds fails *after* Proxmox has stopped the guest and started streaming, so
// catching it here is the difference between a clear refusal and a pointless
// shutdown/restart cycle.
//
// Deliberately conservative: it only blocks on incompatibilities it can prove
// from the storage definitions. Anything it cannot determine — an unknown
// plugin, a missing definition, an unrecognizable volume name — comes back as a
// warning so a migration that would have worked is never refused.
//
//   sourceVolumes   [{ key, volid, storage, storageType }]
//   targetStorageDef  one row of getStorageDefs() ({ storage, type, content })
//   guestType       'lxc' | 'qemu'
export function checkStorageCompatibility({ sourceVolumes = [], targetStorageDef = null, guestType = 'qemu' } = {}) {
  const isLxc = guestType === 'lxc';
  const wanted = isLxc ? 'rootdir' : 'images';

  if (!targetStorageDef || !targetStorageDef.type) {
    return warn('Target storage definition could not be read — storage compatibility was not verified.');
  }
  const name = targetStorageDef.storage || 'target storage';
  const type = String(targetStorageDef.type);

  if (targetStorageDef.disable) {
    return block(`Target storage "${name}" is disabled on the target host.`);
  }

  const content = String(targetStorageDef.content || '').split(',').map((c) => c.trim()).filter(Boolean);
  if (content.length === 0) {
    return warn(`Target storage "${name}" lists no content types — storage compatibility was not verified.`);
  }
  if (!content.includes(wanted)) {
    return block(
      `Target storage "${name}" does not accept ${isLxc ? 'container volumes' : 'VM disk images'} `
      + `(content type "${wanted}"); it holds: ${content.join(', ')}. Pick a storage that lists "${wanted}".`,
    );
  }

  // Beyond content types, only container volumes have a provable format
  // incompatibility. QEMU disk images are converted by Proxmox between every
  // common storage type, so nothing further is asserted for them.
  if (!isLxc) return ok();

  const accepts = targetCtFamilies(type);
  if (!accepts) {
    return warn(`Target storage "${name}" is of unknown type "${type}" — could not verify that it can import the container's volumes.`);
  }

  let unverified = null;
  for (const vol of sourceVolumes || []) {
    const volid = String(vol?.volid || '');
    // Bind mounts and device mount points are not volumes and are not migrated.
    if (!volid.includes(':')) continue;
    const family = sourceCtFamily(volid, vol?.storageType);
    if (!family) {
      unverified = unverified || `Could not determine the on-disk format of ${volid} — storage compatibility was not fully verified.`;
      continue;
    }
    if (accepts.has(family)) continue;
    const described = family === 'image' ? 'a raw disk image' : 'a subvolume/dataset';
    const targetKeeps = accepts.has('subvol') ? 'subvolumes/datasets' : 'raw disk images';
    return block(
      `Target storage "${name}" (${type}) stores container volumes as ${targetKeeps}, but ${vol.key || 'the volume'} `
      + `(${volid}) is ${described}. Proxmox has no matching import/export format for that combination, so the migration `
      + `would abort mid-transfer with "no matching import/export format found for storage '${name}'" — after the `
      + `container has already been stopped. Pick a directory-based target storage, or move the volume to a `
      + `${accepts.has('subvol') ? 'ZFS/BTRFS' : 'directory or LVM'} storage on the source first.`,
    );
  }

  return unverified ? warn(unverified) : ok();
}
