import { btnGhost, btnPrimary, defaultParams, input, inputMono, label, panel } from './WorkflowPageComponents.jsx';

function ParamField({ spec, value, onChange, onFocusField }) {
  const common = { onFocus: onFocusField, 'aria-label': spec.name };
  if (spec.type === 'boolean') return <label className="flex items-center gap-2 py-1 text-sm text-gray-300"><input type="checkbox" checked={value === undefined ? !!spec.default : !!value} onChange={(event) => onChange(event.target.checked)} className="accent-orange-600" /><span className="font-mono text-xs">{spec.name}</span></label>;
  if (spec.type === 'select') return <select {...common} value={value ?? spec.default ?? ''} onChange={(event) => onChange(event.target.value)} className={inputMono}>{(spec.options || []).map((option) => <option key={option} value={option}>{option}</option>)}</select>;
  if (spec.type === 'stringlist') {
    const display = Array.isArray(value) ? value.join(', ') : (value ?? '');
    const update = (text) => onChange(/^\s*\{\{[^}]+\}\}\s*$/.test(text) ? text : text.split(',').map((item) => item.trim()).filter(Boolean));
    return <input {...common} type="text" value={display} onChange={(event) => update(event.target.value)} placeholder="comma,separated or {{token}}" className={inputMono} />;
  }
  if (spec.type === 'json') return <textarea {...common} rows={3} value={typeof value === 'string' ? value : JSON.stringify(value ?? '', null, 2)} onChange={(event) => onChange(event.target.value)} placeholder='{ "key": "value" }' className={`${inputMono} resize-y`} />;
  return <input {...common} type="text" value={value ?? ''} onChange={(event) => onChange(event.target.value)} placeholder={spec.default !== undefined ? String(spec.default) : ''} className={inputMono} />;
}

function StepCard({ step, index, count, actionDef, actions, onChange, onMove, onRemove, onDragStart, onDragOver, onDrop, onFocusField }) {
  const setParam = (name, value) => onChange({ ...step, params: { ...step.params, [name]: value } });
  return <div draggable onDragStart={(event) => onDragStart(event, index)} onDragOver={(event) => onDragOver(event, index)} onDrop={(event) => onDrop(event, index)} className={`${panel} p-3`}>
    <div className="flex items-center gap-2"><span className="cursor-grab select-none px-1 font-mono text-gray-600" title="Drag to reorder" aria-hidden="true">⋮⋮</span><span className={`${label} text-orange-500`}>{String(index + 1).padStart(2, '0')}</span><select value={step.action} onChange={(event) => onChange({ ...step, action: event.target.value, params: defaultParams(actions.find((action) => action.action === event.target.value)) })} className={`${inputMono} max-w-[16rem]`} aria-label="Step action">{actions.map((action) => <option key={action.action} value={action.action}>{action.label}</option>)}</select><input type="text" value={step.step_key || ''} onChange={(event) => onChange({ ...step, step_key: event.target.value })} placeholder="step key" aria-label="Step key" className={`${inputMono} w-28`} /><div className="ml-auto flex items-center gap-1"><button onClick={() => onMove(index, -1)} disabled={index === 0} className={btnGhost} aria-label="Move up">↑</button><button onClick={() => onMove(index, 1)} disabled={index === count - 1} className={btnGhost} aria-label="Move down">↓</button><button onClick={() => onRemove(index)} className="border border-red-600/50 px-2.5 py-1.5 font-mono text-[11px] uppercase text-red-400 hover:bg-red-600/10" aria-label="Remove step">Del</button></div></div>
    {actionDef?.description && <p className="mt-2 text-xs text-gray-500">{actionDef.description}</p>}
    <div className="mt-3 grid grid-cols-1 gap-x-4 gap-y-2 sm:grid-cols-2">{(actionDef?.params || []).map((spec) => <div key={spec.name} className={spec.type === 'json' || spec.type === 'stringlist' ? 'sm:col-span-2' : ''}>{spec.type !== 'boolean' && <label className={`${label} mb-1 block`}>{spec.name}{spec.required && <span className="text-orange-500"> *</span>}{spec.help && <span className="ml-1 lowercase tracking-normal text-gray-600">— {spec.help}</span>}</label>}<ParamField spec={spec} value={step.params?.[spec.name]} onChange={(value) => setParam(spec.name, value)} onFocusField={() => onFocusField(index, spec.name, spec.type)} /></div>)}{(actionDef?.params || []).length === 0 && <p className="text-xs text-gray-600 sm:col-span-2">This action takes no parameters.</p>}</div>
    <div className="mt-3 flex flex-wrap items-center gap-4 border-t border-gray-800 pt-3"><div className="flex items-center gap-2"><span className={label}>condition</span><input type="text" value={step.condition || ''} onChange={(event) => onChange({ ...step, condition: event.target.value })} placeholder="always" aria-label="Run condition" className={`${inputMono} w-48`} onFocus={() => onFocusField(index, '__condition', 'string')} /></div><label className="flex items-center gap-2 text-sm text-gray-300"><input type="checkbox" checked={step.enabled !== 0 && step.enabled !== false} onChange={(event) => onChange({ ...step, enabled: event.target.checked })} className="accent-orange-600" /><span className="font-mono text-[11px] uppercase tracking-wider">Enabled</span></label><label className="flex items-center gap-2 text-sm text-gray-300"><input type="checkbox" checked={!!step.continue_on_error} onChange={(event) => onChange({ ...step, continue_on_error: event.target.checked ? 1 : 0 })} className="accent-orange-600" /><span className="font-mono text-[11px] uppercase tracking-wider">Continue on error</span></label></div>
  </div>;
}

export default function WorkflowEditor({ workflow, trigger, triggerMeta, settings, catalog, actionMap, dirty, saving, setWorkflow, setDirty, setSetting, updateStep, moveStep, removeStep, addStep, onDragStart, onDragOver, onDrop, onFocusField, save, openReset }) {
  return <div className="space-y-4">
    <div className={`${panel} p-4`}><div className="flex flex-wrap items-center gap-3"><div className="flex-1 min-w-[12rem]"><label className={`${label} mb-1 block`}>Workflow name</label><input type="text" value={workflow.name} onChange={(event) => { setWorkflow((current) => ({ ...current, name: event.target.value })); setDirty(true); }} className={input} /></div><label className="mt-5 flex items-center gap-2 text-sm text-gray-300"><input type="checkbox" checked={!!workflow.enabled} onChange={(event) => { setWorkflow((current) => ({ ...current, enabled: event.target.checked ? 1 : 0 })); setDirty(true); }} className="accent-orange-600" /><span className="font-mono text-[11px] uppercase tracking-wider">Enabled</span></label></div><p className="mt-2 text-xs text-gray-600">{triggerMeta?.description}{workflow.is_default ? ' · Currently the built-in default.' : ' · Customized.'}</p>{trigger === 'vlan_provision' && <div className="mt-3 border-t border-gray-800 pt-3"><label className={`${label} mb-1 block`}>Subnet derivation — first octet</label><div className="flex items-center gap-2"><input type="number" min="0" max="255" placeholder="10 (default)" value={settings.subnet?.firstOctet ?? ''} onChange={(event) => setSetting((current, value) => ({ subnet: { ...(current.subnet || {}), firstOctet: value === '' ? undefined : parseInt(value, 10) } }), event.target.value)} className={`${inputMono} w-32`} /><span className="text-xs text-gray-600">Tag 1126 → {(settings.subnet?.firstOctet ?? 10)}.11.26.0/24 · blank keeps the default 10.x.y formula</span></div></div>}</div>
    <div className="space-y-3">{(workflow.steps || []).map((step, index) => <StepCard key={index} step={step} index={index} count={workflow.steps.length} actions={catalog.actions} actionDef={actionMap[step.action]} onChange={(next) => updateStep(index, next)} onMove={moveStep} onRemove={removeStep} onDragStart={onDragStart} onDragOver={onDragOver} onDrop={onDrop} onFocusField={onFocusField} />)}{(workflow.steps || []).length === 0 && <div className={`${panel} p-6 text-center text-sm text-gray-500`}>No steps. Add one below.</div>}</div>
    <div className={`${panel} flex flex-wrap items-center gap-2 p-3`}><span className={label}>Add step</span><select id="add-step-action" defaultValue="" className={`${inputMono} max-w-[16rem]`} aria-label="Action to add"><option value="" disabled>Select action…</option>{catalog.actions.map((action) => <option key={action.action} value={action.action}>{action.label}</option>)}</select><button className={btnGhost} onClick={() => { const element = document.getElementById('add-step-action'); if (element?.value) addStep(element.value); }}>+ Add</button></div>
    <div className="flex flex-wrap items-center gap-2"><button className={btnPrimary} disabled={!dirty || saving} onClick={save}>{saving ? 'Saving…' : dirty ? 'Save changes' : 'Saved'}</button><button className={btnGhost} onClick={openReset}>Reset to default</button>{dirty && <span className="font-mono text-[10px] uppercase tracking-wider text-orange-400">Unsaved changes</span>}</div>
  </div>;
}
