import Modal from '../../components/Modal.jsx';
import { btnGhost, btnPrimary, CallList, label, panel, STATUS_LED } from './WorkflowPageComponents.jsx';

export default function WorkflowModals({ resetOpen, closeReset, doReset, triggerMeta, openRun, closeRun }) {
  return <>
    {resetOpen && <Modal title="Reset workflow" onClose={closeReset} size="sm"><div className="space-y-5 p-5"><p className="text-sm text-gray-300">Reset <span className="font-mono text-orange-300">{triggerMeta?.label}</span> to the built-in default steps and settings? Your customizations for this workflow will be discarded.</p><div className="flex justify-end gap-3"><button className={btnGhost} onClick={closeReset}>Cancel</button><button className={btnPrimary} onClick={doReset}>Reset</button></div></div></Modal>}
    {openRun && <Modal title={`Run log — ${openRun.subject_label || openRun.subject_type}`} onClose={closeRun} size="xl"><div className="space-y-4 p-5"><div className="flex flex-wrap items-center gap-3 text-sm"><span className={`aaris-led ${STATUS_LED[openRun.status] || 'aaris-led--off'}`} /><span className="font-mono uppercase tracking-wider text-gray-300">{openRun.status}</span><span className="text-gray-600">·</span><span className="text-gray-500">{openRun.trigger}</span><span className="text-gray-600">·</span><span className="text-gray-500">{openRun.created_at}</span></div><div className="space-y-2">{(openRun.log || []).map((entry, index) => <div key={index} className={`${panel} p-3`}><div className="flex items-center gap-2"><span className={`aaris-led ${STATUS_LED[entry.status] || 'aaris-led--off'}`} /><span className="font-mono text-[11px] text-gray-300">{entry.label || entry.action}</span><span className="ml-auto font-mono text-[10px] uppercase text-gray-600">{entry.status}</span></div>{entry.summary && <p className="mt-1 text-xs text-gray-500">{entry.summary}</p>}{entry.error && <p className="mt-1 text-xs text-red-400">{entry.error}</p>}{entry.artifacts?.length > 0 && <p className="mt-1 font-mono text-[10px] text-gray-600">created: {entry.artifacts.join(', ')}</p>}<CallList calls={entry.calls} />{entry.reverted && <div className="mt-1 space-y-0.5">{entry.reverted.map((reverted, revertedIndex) => <p key={revertedIndex} className={`font-mono text-[10px] ${reverted.ok ? 'text-gray-500' : 'text-red-400'}`}>rollback: {reverted.artifact} {reverted.ok ? '✓' : `✗ ${reverted.error}`}</p>)}</div>}</div>)}</div>{openRun.artifacts?.length > 0 && <div><h4 className={`${label} mb-1`}>Recorded artifacts ({openRun.artifacts.length})</h4><pre className="overflow-x-auto border border-gray-800 bg-gray-950 p-2 font-mono text-[10px] text-gray-400">{JSON.stringify(openRun.artifacts, null, 2)}</pre></div>}</div></Modal>}
  </>;
}
