import { btnGhost, CallList, inputMono, label, panel, STATUS_LED } from './WorkflowPageComponents.jsx';

const FORMS = {
  vlan: [['tag', 'VLAN tag', '1126', 'number'], ['name', 'Name', 'lab-net']],
  policy: [['srcInterface', 'Src interface', 'vlan1126'], ['dstInterface', 'Dst interface', 'vlan1127']],
};

function DryRunInputs({ trigger, inputs, setInputs }) {
  const set = (key, value) => setInputs((previous) => ({ ...previous, [key]: value }));
  const field = ([key, fieldLabel, placeholder, type = 'text']) => <div key={key}><label className={`${label} mb-1 block`}>{fieldLabel}</label><input type={type} value={inputs[key] ?? ''} onChange={(event) => set(key, event.target.value)} placeholder={placeholder} className={`${inputMono} w-full`} aria-label={key} /></div>;
  if (trigger === 'vlan_provision' || trigger === 'vlan_deprovision') return <div className="space-y-2">{FORMS.vlan.map(field)}<div className="flex gap-4"><label className="flex items-center gap-1.5 text-xs text-gray-300"><input type="checkbox" checked={inputs.allowInternet !== false} onChange={(event) => set('allowInternet', event.target.checked)} className="accent-orange-600" />internet</label><label className="flex items-center gap-1.5 text-xs text-gray-300"><input type="checkbox" checked={inputs.enableDhcp !== false} onChange={(event) => set('enableDhcp', event.target.checked)} className="accent-orange-600" />dhcp</label></div></div>;
  if (trigger === 'port_forward_create' || trigger === 'port_forward_delete') return <div className="space-y-2">{field(['name', 'Name', 'web-http'])}<div className="grid grid-cols-2 gap-2"><div><label className={`${label} mb-1 block`}>Protocol</label><select value={inputs.protocol || 'tcp'} onChange={(event) => set('protocol', event.target.value)} className={`${inputMono} w-full`}><option value="tcp">tcp</option><option value="udp">udp</option></select></div>{field(['externalPort', 'Ext port', '8080', 'number'])}{field(['internalIp', 'Internal IP', '10.11.26.50'])}{field(['internalPort', 'Internal port', '80', 'number'])}<div className="col-span-2">{field(['vlanInterface', 'VLAN interface', 'vlan1126'])}</div></div></div>;
  if (trigger === 'policy_create' || trigger === 'policy_delete') return <div className="space-y-2">{FORMS.policy.map(field)}<label className="flex items-center gap-1.5 text-xs text-gray-300"><input type="checkbox" checked={inputs.bidirectional === true} onChange={(event) => set('bidirectional', event.target.checked)} className="accent-orange-600" />bidirectional</label></div>;
  return <p className="text-xs text-gray-600">No inputs for this trigger.</p>;
}

export default function WorkflowSidebar({ variables, insertVariable, trigger, dryInputs, setDryInputs, runDryRun, dryRunning, dryResult, runs, viewRun }) {
  return <div className="space-y-4">
    <div className={`${panel} p-4`}><h3 className={`${label} mb-2`}>Variables</h3>{variables.length === 0 ? <p className="text-xs text-gray-600">This trigger performs artifact-based teardown — no template variables.</p> : <><p className="mb-2 text-[11px] text-gray-600">Focus a field, then click to insert (or copy).</p><div className="flex flex-wrap gap-1.5">{variables.map((variable) => <button key={variable} onClick={() => insertVariable(variable)} className="border border-gray-700 px-1.5 py-0.5 font-mono text-[10px] text-gray-400 hover:border-orange-600 hover:text-orange-300">{variable}</button>)}</div></>}</div>
    <div className={`${panel} p-4`}><h3 className={`${label} mb-2`}>Dry-run preview</h3><DryRunInputs trigger={trigger} inputs={dryInputs} setInputs={setDryInputs} /><button className={`${btnGhost} mt-2`} onClick={runDryRun} disabled={dryRunning}>{dryRunning ? 'Rendering…' : 'Preview calls'}</button>{dryResult && <div className="mt-3 space-y-2">{dryResult.preview.map((item) => <div key={item.position} className="border border-gray-800 bg-gray-950/60 p-2"><div className="flex items-center gap-2"><span className={`aaris-led ${item.error ? 'aaris-led--error' : item.skipped ? 'aaris-led--off' : 'aaris-led--ok'}`} /><span className="font-mono text-[11px] text-gray-300">{item.label}</span>{item.skipped && <span className="font-mono text-[10px] uppercase text-gray-600">{item.skipped}</span>}</div>{item.error && <p className="mt-1 text-[11px] text-red-400">{item.error}</p>}<CallList calls={item.calls} /></div>)}</div>}</div>
    <div className={`${panel} p-4`}><h3 className={`${label} mb-2`}>Recent runs</h3>{runs.length === 0 ? <p className="text-xs text-gray-600">No runs recorded yet.</p> : <div className="space-y-1">{runs.map((run) => <button key={run.id} onClick={() => viewRun(run.id)} className="flex w-full items-center gap-2 border border-gray-800 px-2 py-1.5 text-left hover:border-gray-600"><span className={`aaris-led ${STATUS_LED[run.status] || 'aaris-led--off'}`} /><span className="font-mono text-[11px] text-gray-300">{run.subject_label || run.subject_id || run.subject_type}</span><span className="ml-auto font-mono text-[10px] uppercase text-gray-600">{run.status}</span></button>)}</div>}</div>
  </div>;
}
